name: 'verify-build'

on:
  push:
    tags:
      - ^[0-9].*
    branches:
      - custombuild
  pull_request:
    branches:
      - custombuild

defaults:
  run:
    shell: bash

jobs:
  maven:
    name: 'maven-build'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build with Maven
        run: bin/mvn-deploy-github.sh
        env:
          GH_REPO: ${{ env.GITHUB_REPOSITORY }}
          GH_DEPLOY_USERNAME: ${{ env.GITHUB_REPOSITORY_OWNER }}
          GH_DEPLOY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: prepare artifact
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd target
          cp *.jar ${{ github.event.repository.name }}-${{ github.ref_name }}.jar
          ls -lah

      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: target/${{ github.event.repository.name }}-${{ github.ref_name }}.jar
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
